"""create merchant provider persistence foundation

Revision ID: aa4e231fa1b0
Revises:
Create Date: 2026-08-22 03:54:30.411405
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'aa4e231fa1b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_merchant_id'), 'analyses', ['merchant_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nonce_hash')
    )
    op.create_index(op.f('ix_oauth_states_merchant_id'), 'oauth_states', ['merchant_id'], unique=False)
    op.create_table('provider_connections',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transactions_imported', sa.Integer(), nullable=False),
    sa.Column('webhook_status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'provider', name='uq_merchant_provider_connection')
    )
    op.create_index(op.f('ix_provider_connections_merchant_id'), 'provider_connections', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_provider_connections_provider_account_id'), 'provider_connections', ['provider_account_id'], unique=False)
    op.create_table('raw_provider_objects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_object_type', sa.String(length=100), nullable=False),
    sa.Column('provider_object_id', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'provider', 'provider_object_type', 'provider_object_id', name='uq_raw_provider_object')
    )
    op.create_index(op.f('ix_raw_provider_objects_merchant_id'), 'raw_provider_objects', ['merchant_id'], unique=False)
    op.create_table('analysis_insights',
    sa.Column('insight_id', sa.String(length=100), nullable=False),
    sa.Column('analysis_id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id', 'analysis_id')
    )
    op.create_index(op.f('ix_analysis_insights_merchant_id'), 'analysis_insights', ['merchant_id'], unique=False)
    op.create_table('canonical_transactions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'provider', 'provider_transaction_id', name='uq_canonical_provider_transaction')
    )
    op.create_index('ix_canonical_analysis', 'canonical_transactions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_merchant_id'), 'canonical_transactions', ['merchant_id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_normalised', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_id'], ['provider_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_connection_id'), 'sync_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_merchant_id'), 'sync_jobs', ['merchant_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_object_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_object_id'], ['raw_provider_objects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_webhook_event')
    )
    op.create_index(op.f('ix_webhook_events_merchant_id'), 'webhook_events', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_merchant_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_sync_jobs_merchant_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_connection_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_canonical_transactions_merchant_id'), table_name='canonical_transactions')
    op.drop_index('ix_canonical_analysis', table_name='canonical_transactions')
    op.drop_table('canonical_transactions')
    op.drop_index(op.f('ix_analysis_insights_merchant_id'), table_name='analysis_insights')
    op.drop_table('analysis_insights')
    op.drop_index(op.f('ix_raw_provider_objects_merchant_id'), table_name='raw_provider_objects')
    op.drop_table('raw_provider_objects')
    op.drop_index(op.f('ix_provider_connections_provider_account_id'), table_name='provider_connections')
    op.drop_index(op.f('ix_provider_connections_merchant_id'), table_name='provider_connections')
    op.drop_table('provider_connections')
    op.drop_index(op.f('ix_oauth_states_merchant_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_analyses_merchant_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('merchants')
    # ### end Alembic commands ###
